---
- include: include_vars.yml

- name: Check if android studio is installed
  command: grep {{android_sdk_build}} /opt/android-sdk-{{package_ext}}
  register: installed
  failed_when: False
  changed_when: False

- name: set should_run fact
  set_fact:
    should_run: installed.rc != 0

- include: sudoorbecome.yml
